### ISSUE TITLE
Identical repo slug issue

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/directory#62]
@KTS915 @xxsimoxx So I ran a test using Shortcodes Everywhere plugin as an example and we may have a problem.

Original:
- Repo: `https://github.com/xxsimoxx/codepotent-shortcodes-everywhere/`
- Download URL: `https://github.com/xxsimoxx/codepotent-shortcodes-everywhere/releases/download/1.1.2/codepotent-shortcodes-everywhere-1.1.2.zip`
- Slug: `codepotent-shortcodes-everywhere`

Duplicate submitted by me:
- Repo: `https://github.com/viktorix/codepotent-shortcodes-everywhere/`
- Download URL: `https://github.com/viktorix/codepotent-shortcodes-everywhere/releases/download/1.1.2/codepotent-shortcodes-everywhere-1.1.2.zip`
- Slug: `codepotent-shortcodes-everywhere-1.1.2`

As you can see, the directory generated a slug based on the zip file name which includes the version number with periods.

Can we generate our own slug using org and repo slug? For example, my duplicate plugin `viktorix/codepotent-shortcodes-everywhere` would be `viktorix-codepotent-shortcodes-everywhere`.

In addition, since my duplicate plugin's name is also Shortcodes Everywhere, the CPT slug is `shortcodes-everywhere-2`. That -2 isn't going to look good. This touches on issue #36. I think we need to improve the slug generation for CPTs too. What if we used API slug from above for CPT slug too? Save us any future trouble. Or even append it with CPT ID or random numbers.

Instead of:
`https://staging-directory.classicpress.net/plugins/shortcodes-everywhere-2/`

It would be: 
`https://staging-directory.classicpress.net/plugins/viktorix-shortcodes-everywhere/`

You can see meta data for my duplicate plugin here:
https://staging-directory.classicpress.net/wp-admin/post.php?post=2013&action=edit

**Comment by xxsimoxx** [comment]
Digging into this, the problem is with the ZIP file used to test.
`codepotent-shortcodes-everywhere-1.1.2.zip` should expand to a folder named `codepotent-shortcodes-everywhere` but it expand to `codepotent-shortcodes-everywhere-1.1.2`.
Even ClassicPress let me install it.

<img width="301" alt="image" src="https://user-images.githubusercontent.com/29772709/212262983-39c74c5e-9458-4a95-98ad-83f7fcb871e2.png">

Of course it can't be activate because `PHP Fatal error: Cannot declare class CodePotent\ShortcodesEverywhere\ShortcodeEnabler` 

One of the possible commands to generate a ZIP file is `git archive -o "${slug}-${version}.zip" --prefix ${slug}/ HEAD`, where setting `--prefix` will fix this issue.

At that point the directory should refuse the plugin, and also ClassicPress will ask what to do.

<img width="659" alt="image" src="https://user-images.githubusercontent.com/29772709/212263606-d82e5d1b-6887-430d-857b-c51e0b4c92aa.png">

**Comment by viktorix** [comment]
I will re-test. I just downloaded Github's automatically generated zip and uploaded that for a release. 

@xxsimoxx do you think we should perform a check on a slug to make sure it doesn't have any special characters? Maybe validate that it's alphanumeric with dashes only. Reject anything that fails:
```
function is_slug($str) {
    return preg_match('/^[a-z0-9]+(-?[a-z0-9]+)*$/i', $str);
}
```

**Comment by xxsimoxx** [comment]
As now there are some two checks on slugs:
- at submission to prevent duplicated slugs;
- on update to check that slug is not changing.

We can introduce a regex to enforce that  but I've seen strange slugs over time and CP accepted those.
So maybe we can check the slug during reviews, where we can explain in a clear way what the problem is, instead of a generic "bad slug" in the submission process.
This because depending on their release process generating a good zip can be challenging.

**Comment by viktorix** [comment]
> This because depending on their release process generating a good zip can be challenging.

I simply downloaded auto-generated zip to the release. I assume some people might do that too, instead of properly generating a zip. So we could end up with bad zips submitted. Can we check for that (what folder zip expands to) during submission and provide a link to an article about generating proper zip? 

We can always catch issues in review, but we should try to streamline and automate the process to reduce workload on the review team.

**Comment by xxsimoxx** [comment]
Agree.
We just have to put down a regex to validate a slug.
`/^[a-z0-9\-]+$/` is ideal. 

`/^[a-zA-Z0-9_\-]+$/` is more flexible and excluding dots can catch up this kind of issues.
